<h1 align=center><font size = 5>Numpy in Python</font></h1>

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

 Consider the list **a **, the list contains three nested lists **each of equal size**. 

In [2]:
a=[[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

 We can cast the list to a numpy array  as follow

In [3]:
#every elment if of the same type 
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

We can use the attribute **ndim** to obtain the number of axes or dimensions referred to as the rank. 

In [4]:
A.ndim

2

 Attribute **shape** returns a tuple corresponding to the size or number of each dimension.

In [5]:
A.shape

(3, 3)

The total number of elements in the array is given by the attribute **size**.

In [6]:
A.size

9

### Accessing different elements of an Numpy Array 

 We can use rectangular brackets to access the different elements of the array,The correspondence  between the rectangular brackets and the list and the rectangular representation is a following 3x3 array:  

In [7]:
A[1,2]

23

 We simply use the square brackets and the indices corresponding to the element we would like:

 We can also use the following notation to obtain the elements: 

In [8]:
A[1][2]

23

In [9]:
A[0][0]

11

 We can also use **slicing** in numpy arrays; we would like to obtain the first two columns in the first row  

 This can be done with the following syntax 

In [10]:
 A[0][0:2]

array([11, 12])

Similarly, we can obtain the first two rows of the 3rd column as follows:

In [11]:
A[0:2,2]

array([13, 23])

# Basic Operations 

 We can also add arrays; the process is identical to matrix addition. Matrix addition of **X** and **Y** :

 The numpy array is given by **X** and **Y**

In [12]:
X=np.array([[1,0],[0,1]]) 
X

array([[1, 0],
       [0, 1]])

In [13]:
Y=np.array([[2,1],[1,2]]) 
Y

array([[2, 1],
       [1, 2]])

 We can add the numpy arrays as follows.

In [14]:
Z=X+Y
Z

array([[3, 1],
       [1, 3]])

 Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix **Y** by the scaler 2, we simply multiply every element in the matrix by 2.

 We can perform the same operation in numpy as follows 

In [15]:
Y=np.array([[2,1],[1,2]]) 
Y

array([[2, 1],
       [1, 2]])

In [16]:
Z=2*Y
Z

array([[4, 2],
       [2, 4]])

 Multiplication of two arrays corresponds to an element-wise product or  Hadamard product.  Consider matrix  **X** and **Y**. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same colour boxes together. The result is a new matrix that is the same size as matrix **Y** or **X**

We can perform element-wise product of the array **X** and **Y** as follows:

In [17]:
Y=np.array([[2,1],[1,2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
X=np.array([[1,0],[0,1]]) 
X

array([[1, 0],
       [0, 1]])

In [19]:
Z=X*Y
Z

array([[2, 0],
       [0, 2]])

 We can also perform matrix multiplication with the numpy arrays **A** and **B** as follows:

 First, we define matrix **A** and **B**:

In [20]:
A=np.array([[0,1,1],[1,0,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [21]:
B=np.array([[1,1],[1,1],[-1,1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function **dot** to multiply the arrays together.

In [22]:
Z=np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [ ]:
np.sin(Z)

In [ ]:
C=np.array([[1,1],[2,2],[3,3]])
C

In [ ]:
C.T